    echo "Set up the basic requirements of a project."
	echo "Project		- Your project's name"
	echo "Lang			- Your project's language (C)"
	echo "Directory		- Where should this project be created"
	echo "-h			- Display this help message"